os:
  - linux
  - osx
language: node_js
node_js:
  - "6.0.x"
before_script:
  - npm i -g bower webpack mocha-phantomjs typescript
  - npm link typescript
  - bower install
  - npm run build
script:
  - npm test
